#!/bin/bash
# Version 20

qtMinVer="6.6"
kfMinVer="6.0"
plasmaMinVer="6.0"
filenameTag="plasma${plasmaMinVer}"
filenameTag=`echo "$filenameTag" | sed 's/\./\_/'`
python3 ./kpac build --tag "$filenameTag"
